export const Skill_data: Skill_data[] = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Json Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Tauri",
    Image: "/tauri.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Nigx",
    Image:
      "https://i0.wp.com/thinkground.studio/wp-content/uploads/2019/04/190415_Nginx-Logo.png?fit=423%2C401&ssl=1",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Go",
    Image: "/go.png",
    width: 60,
    hight: 60,
  },
  {
    skill_name: "Gin gonic",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];

export const Frontend_skill: Skill_data[] = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
];

export const Backend_skill: Skill_data[] = [
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
];

export const Full_stack: Skill_data[] = [
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Tauri",
    Image: "/tauri.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Nigx",
    Image:
      "https://i0.wp.com/thinkground.studio/wp-content/uploads/2019/04/190415_Nginx-Logo.png?fit=423%2C401&ssl=1",
    width: 60,
    hight: 60,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Gin gonic",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
];

export const Other_skill: Skill_data[] = [
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Json Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
];

export const Other_skill2: Skill_data[] = [
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },

  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];
export const Other_skill3: Skill_data[] = [
  {
    skill_name: "Go",
    Image: "/go.png",
    width: 60,
    hight: 60,
  },
];

export const Project: Project_data[] = [
  {
    title: "Morden Next js 13 Profiol",
    video_key: "HvkrAjHJ-38",
    say_xi: "Xi Have a Gread Day ☘️ ",
    say_xi_blog:
      "This is My Profiol Project For Showcase , basic Ui interface and Contain Basic Animation & Authentication  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Framer Motion",
    ],
    about_this_app:
      "Contain StarMode , Drop Down NavBar , Authentication Google , Facebook , Github , Instgram , Custom Star Colour Basic Animation With Fraimer Motion , Conatin Embed Youtube Video ",
    design_blog: " Ui/Ux Desing & All Code Written by Me  ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "framer-motion",
      "maath",
      "react-redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/HyatMyat_Profiol/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/profiol3.png",
    project_blog:
      "Contain StarMode , Authentication Google , Facebook , Github , Instgram , Custom Star Colour Basic Animation With Fraimer Motion",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Shoe Ecommerce & AdminDashboard ",
    video_key: "v3LJMcWbcDQ",
    say_xi: "Hello my friends 👟",
    say_xi_blog:
      "Xi That is My  Fullstack Responsive Shoes Project I get A lot of SKill Form This Project Complex Ui , authentication , CRUD 💚💚 ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/shoemap.png",
    project_blog:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "AdminDashboard Web app",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Xi Form Responsive Food Project🤤",
    say_xi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/foodd.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Deliveroo Mobile App",
    video_key: "AxQ_Eli8gtk",
    say_xi: "Xi from my first mobile app 📱",
    say_xi_blog:
      "ReactNative First Project With Expo CLI Conatain Google AUthentication Contain Basic RestApi and Google Maps functionality ",
    technology_feature: [
      "Tailwind",
      "React Native",
      "Redux",
      "Type Script",
      "Expo",
      "Node js",
      "Express js",
      "Postger sql",
    ],

    about_this_app:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    design_blog: "Desing From PapaReact YouTube Channel",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case we use Yarn and since this project was developed using expo we can also use the expo-cli to install the dependencies.",
    package: [
      "expo",
      "react-native-gesture-handler",
      "react-native-heroicons",
      "react-native-maps",
      "react-native-progress",
      "react-native-safe-area-context",
      "react-native-screens",
      "react-native-svg",
      "react-redux",
      "typescript",
      "nativewind",
      "expo-splash-screen",
      "@react-navigation/native",
      "@react-native-masked-view/masked-view",
      "@react-native-async-storage/async-storage",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo_Mobile.apk/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "",
    project_blog:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    Type: "React Native",
    project_Img_Mobile: [
      "/deliveroo1.jpg",
      "/roo2.jpg",
      "/roo3.jpg",
      "/roo4.jpg",
      "/roo5.jpg",
    ],
    indevelopment: false,
  },
  {
    title: "FullStackFood Order Website",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Xi Form Responsive Food Project🤤",
    say_xi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/foodorder.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
  },

  {
    title: "Fullstack AI ChatGPT ( Clone ) ",
    video_key: "R90bxY4UwPg",
    say_xi: "Xello My Frends 💚",
    say_xi_blog:
      "This is my First AI Project data Coming From Opend AI , You can asked like RealTime Chat GPT   ",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],

    about_this_app:
      "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
    design_blog: "Desing From Realworld ChatGPT",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm ",
    package: [
      "@reduxjs/toolkit",
      "@uiball/loaders",
      "firebase",
      "firebase-admin",
      "nextjs-progressbar",
      "openai",
      "react-firebase-hooks",
      "react-icons",
      "react-redux",
      "react-simple-typewriter",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Chat_GPT4/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/gpt2.png",
    project_blog:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Nike AdminDashboard Web App ",
    video_key: "v3LJMcWbcDQ",
    say_xi: "Hello my friends 👟",
    say_xi_blog:
      "Xi That is My  Fullstack Responsive Shoes Project I get A lot of SKill Form This Project Complex Ui , authentication , CRUD 💚💚 ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/nikedash.png",
    project_blog:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Morden 3 js Profiol",
    video_key: "6wzf2ho-kzI",
    say_xi: "Hello my friend! 👋🏼",
    say_xi_blog:
      "This is a Normal 3 js Responsive Profiol Website Constain Starts Mode , Background Music , Day and Light Mode , Contain youtube emb video like youtube Mobile Responsive desing Base on Vite ",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Threes js",
      "Framer Motion",
    ],
    about_this_app:
      "This Responsive  Website is Make for showcase Project Profile ",
    design_blog:
      "very basic desing from My Friends , and I ReModified It All Code & Desing by Me ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I use npm beacuse We use older npm package .",
    package: [
      " maath",
      " @react-three/fiber",
      " @emailjs/browser",
      " framer-motion",
      " @react-three/fiber ",
      " @reduxjs/toolkit ",
      " react-router-dom",
      " react-tilt",
      " react-simple-typewriter",
      " react-icons",
      " react-spinkit",
      " react-vertical-timeline-component",
      " three",
    ],
    conclusion_blog:
      "As I said at the beginning, this is a great project for begginers and even for those who are not new to React . I bealive this is a grat project to have in a resume or portfolio. I am very happy with the app and I hope you will enjoy it as well.",
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Profiol_2/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/Untitled-1.png",
    project_blog:
      "Morden Profiol Wbsite With Javascript | React | Tailwind css | Responsive Website profiol desing.",
    Type: "React",
    indevelopment: false,
  },
  {
    title: "ApexLegnds.com ( Clone )",
    video_key: "IqYbA6ZZ-e4",
    say_xi: "Hi have a good day! ☘️",
    say_xi_blog: "That is My  favourite game Website so i can make Clone one",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
    ],

    about_this_app:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive  and Contain Embed video",
    design_blog: "Desing From Apexlegends.com , I Recreate That Design",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@reduxjs/toolkit",
      "next",
      "react-icons",
      "react-redux",
      "swiper",
      "typescript",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/IqYbA6ZZ-e4",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/ApexLegends.com/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/apex.png",
    project_blog:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Full Stack SocalMedia ",
    video_key: "cLKsNVSyPMM",
    say_xi: "Hello my Friends 🎉",
    say_xi_blog:
      "Fullstack Social Media Project With  React , Tailwind css and My First Node js express Server ☘️ ",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Node js",
      "Express js",
    ],
    about_this_app:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
    design_blog:
      "Basic Desing From Youtube and I Modified That Desing All Code By Me an My Own Desing ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@mui/icons-material",
      "@reduxjs/toolkit",
      "formik",
      "javascript-time-ago",
      "jwt-decode",
      "material-ui-popup-state",
      "pusher-js",
      "react-dropzone",
      "react-easy-crop",
      "react-icons",
      "react-redux",
      "react-router-dom",
      "redux-persist",
      "swiper",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/cLKsNVSyPMM",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
    project_image: "/reactsocialmedia1.png",
    project_blog:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    Type: "React",
    indevelopment: false,
  },
  {
    title: "Profiol Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: ["Golang", "Gin", "Mongo db", "JWT"],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/goserver.png",
    project_blog:
      "My First Go , Gin Server , Basic CRUD Go Server With Mongodb",
    Type: "server",
    indevelopment: true,
  },
  {
    title: "ShoeEcommerce Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "JWT",
      "Stripe",
    ],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      " User authentication Google auth , Facebook auth , Nike Auth ..more , Mind leven CRUD functionality",
    Type: "server",
    indevelopment: false,
  },
  {
    title: "FoodOrder & AdminDashboard",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      "User authentication , Graphql  Mind leven CRUD functionality , Google auth , Facebook auth , Fastfood Auth,",
    Type: "server",
    indevelopment: false,
  },
  {
    title: "Deliveroo Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Postger sql",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      "Node js Express With Postger Sql ,FireBase FireStore  CRUD functionality",
    Type: "server",
    indevelopment: false,
  },
];

export const colour: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
];

/*
  {
    title: "",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    project_blog: "",
    Type: "Next js 13",
    indevelopment: false,
  },
*/
